# https://quay.io/repository/minio/minio
# https://hub.docker.com/_/postgres
# https://hub.docker.com/_/adminer
# https://hub.docker.com/r/dpage/pgadmin4
version: '3.5'

services:

  minio:
    container_name: minio_container
    image: quay.io/minio/minio:RELEASE.2022-08-22T23-53-06Z
    environment:
      MINIO_ROOT_USER: AKIAIOSFODNN7EXAMPLE
      MINIO_ROOT_PASSWORD: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio:/data
    command:
      - server
      - /data
      - --console-address
      - ":9001"
    restart: unless-stopped

  postgres:
    container_name: postgres_container
    image: postgres:14.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sandbox
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/db.sql
      - ./postgres14:/var/lib/postgresql/data
    restart: unless-stopped

  adminer:
    container_name: adminer_container
    image: adminer:4.8.1
    ports:
      - "9090:8080"
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:6.12
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pga@pga.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-pga}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    restart: unless-stopped

volumes:
  pgadmin:
