// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/sdreger/lib-file-processor-go/filestore (interfaces: BlobStore)

// Package filestore is a generated GoMock package.
package filestore

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockBlobStore is a mock of BlobStore interface.
type MockBlobStore struct {
	ctrl     *gomock.Controller
	recorder *MockBlobStoreMockRecorder
}

// MockBlobStoreMockRecorder is the mock recorder for MockBlobStore.
type MockBlobStoreMockRecorder struct {
	mock *MockBlobStore
}

// NewMockBlobStore creates a new mock instance.
func NewMockBlobStore(ctrl *gomock.Controller) *MockBlobStore {
	mock := &MockBlobStore{ctrl: ctrl}
	mock.recorder = &MockBlobStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBlobStore) EXPECT() *MockBlobStoreMockRecorder {
	return m.recorder
}

// CreateBucket mocks base method.
func (m *MockBlobStore) CreateBucket(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBucket", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateBucket indicates an expected call of CreateBucket.
func (mr *MockBlobStoreMockRecorder) CreateBucket(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBucket", reflect.TypeOf((*MockBlobStore)(nil).CreateBucket), arg0, arg1)
}

// StoreObject mocks base method.
func (m *MockBlobStore) StoreObject(arg0 context.Context, arg1, arg2, arg3 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreObject", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StoreObject indicates an expected call of StoreObject.
func (mr *MockBlobStoreMockRecorder) StoreObject(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreObject", reflect.TypeOf((*MockBlobStore)(nil).StoreObject), arg0, arg1, arg2, arg3)
}
