// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/sdreger/lib-file-processor-go/scrapper (interfaces: BookDataScrapper)

// Package scrapper is a generated GoMock package.
package scrapper

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	book "github.com/sdreger/lib-file-processor-go/domain/book"
)

// MockBookDataScrapper is a mock of BookDataScrapper interface.
type MockBookDataScrapper struct {
	ctrl     *gomock.Controller
	recorder *MockBookDataScrapperMockRecorder
}

// MockBookDataScrapperMockRecorder is the mock recorder for MockBookDataScrapper.
type MockBookDataScrapperMockRecorder struct {
	mock *MockBookDataScrapper
}

// NewMockBookDataScrapper creates a new mock instance.
func NewMockBookDataScrapper(ctrl *gomock.Controller) *MockBookDataScrapper {
	mock := &MockBookDataScrapper{ctrl: ctrl}
	mock.recorder = &MockBookDataScrapperMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBookDataScrapper) EXPECT() *MockBookDataScrapperMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockBookDataScrapper) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockBookDataScrapperMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockBookDataScrapper)(nil).Close))
}

// GetBookData mocks base method.
func (m *MockBookDataScrapper) GetBookData(arg0 string) (book.ParsedData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBookData", arg0)
	ret0, _ := ret[0].(book.ParsedData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBookData indicates an expected call of GetBookData.
func (mr *MockBookDataScrapperMockRecorder) GetBookData(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBookData", reflect.TypeOf((*MockBookDataScrapper)(nil).GetBookData), arg0)
}
